version: '3'

networks:
  dev:

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    hostname: mysql
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      SERVICE_NAME: mysql
    ports:
      - "9906:3306"
    networks:
      - dev

  web:
    build: .
    container_name: web
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html/
    networks:
      - dev
    ports:
      - "8100:80"
    stdin_open: true
    tty: true